server:
  port: 8081
logging:
  level:
    root: INFO
  file:
    name: /var/log/spring/worker.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teste?useSSL=false
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
    queue: worker.process
    listener:
      simple:
        prefetch: 10
        acknowledge-mode: MANUAL
  redis:
    host: localhost
    port: 6389
    portCache: 6379
    pub: pub
    password:
  data:
    mongodb:
      uri: mongodb://localhost/worker
      port: 27017
      host: localhost
      database: worker