server:
  port: 8081
logging:
  level:
    root: INFO
  file:
    name: /var/log/spring/worker.log
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    queue: worker.process
    listener:
      simple:
        prefetch: 10
        acknowledge-mode: MANUAL
  redis:
    host: localhost
    port: 6389
    portCache: 6379
    pub: pub
    password:
  data:
    mongodb:
      uri: mongodb://localhost/worker
      port: 27017
      host: localhost
      database: worker